apiVersion: apps/v1
kind: Deployment
metadata:
  name: ra-completion
  namespace: ra-completion
  labels:
    app: perl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perl
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: perl
    spec:
      restartPolicy: Always

      containers:
      - name: ra-completion
        image: alpine:3.14
        command: ["/bin/sh"]
        args: [
         "-c",
         "(
              wget -O - https://raw.githubusercontent.com/lordslair/ra-completion/master/code/entrypoint.sh | sh
          ) || echo 1"
        ]
        env:
        - name: RAUSER
          valueFrom:
            secretKeyRef:
              name: ra-completion
              key: RAUSER
        - name: RAKEY
          valueFrom:
            secretKeyRef:
              name: ra-completion
              key: RAKEY
        - name: TWITTCK
          valueFrom:
            secretKeyRef:
              name: ra-completion
              key: TWITTCK
        - name: TWITTST
          valueFrom:
            secretKeyRef:
              name: ra-completion
              key: TWITTST
        - name: TWITTAT
          valueFrom:
            secretKeyRef:
              name: ra-completion
              key: TWITTAT
        - name: TWITTTS
          valueFrom:
            secretKeyRef:
              name: ra-completion
              key: TWITTTS
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: ra-completion
              key: sql-db
        - name: SQL_DBHOST
          valueFrom:
            secretKeyRef:
              name: ra-completion
              key: sql-host
        - name: SQL_DBPORT
          valueFrom:
            secretKeyRef:
              name: ra-completion
              key: sql-port
        - name: SQL_DBPASS
          valueFrom:
            secretKeyRef:
              name: ra-completion
              key: sql-pass
        - name: SQL_DBUSER
          valueFrom:
            secretKeyRef:
              name: ra-completion
              key: sql-user
