apiVersion: apps/v1
kind: Deployment
metadata:
  name: ra-completion
  labels:
    app: perl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perl
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: perl
    spec:
      initContainers:
      - name: ra-completion-perl-init
        image: busybox
        volumeMounts:
        - name: code
          mountPath: /code
        command: ["/bin/sh"]
        args: [
         "-c",
         "(
              wget   https://github.com/lordslair/ra_bot/archive/master.zip -O /tmp/ra_bot.zip &&
              unzip  /tmp/ra_bot.zip -d /tmp/ &&
              cp -a  /tmp/ra_bot-master/code/* /code/ &&
              rm -rf /tmp/ra_bot-master /tmp/ra_bot.zip
          ) || echo 1"
        ]
      containers:
      - name: ra-completion
        image: alpine
        command: ["/code/entrypoint.sh"]
        env:
        - name: RAUSER
          value: <RetroAchievement.org userneme>
        - name: RAKEY
          value: <RetroAchievement.org apikey>
        - name: TWITTCK
          value: <Twitter consumer_key>
        - name: TWITTST
          value: <Twitter consumer_secret>
        - name: TWITTAT
          value: <Twitter access_token>
        - name: TWITTTS
          value: <Twitter access_token_secret>
        volumeMounts:
        - mountPath: /code
          name: code
      restartPolicy: Always
      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: ra-completion-code-perl
