apiVersion: apps/v1
kind: Deployment
metadata:
  name: ra-completion
  labels:
    app: perl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perl
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: perl
    spec:
      restartPolicy: Always

      containers:
      - name: ra-completion
        image: alpine
        command: ["/bin/sh"]
        args: [
         "-c",
         "(
              wget -O - https://raw.githubusercontent.com/lordslair/ra_bot/master/code/entrypoint.sh | sh
          ) || echo 1"
        ]
        env:
        - name: RAUSER
          value: <RetroAchievement.org userneme>
        - name: RAKEY
          value: <RetroAchievement.org apikey>
        - name: TWITTCK
          value: <Twitter consumer_key>
        - name: TWITTST
          value: <Twitter consumer_secret>
        - name: TWITTAT
          value: <Twitter access_token>
        - name: TWITTTS
          value: <Twitter access_token_secret>
