apiVersion: v1
kind: Secret
metadata:
  namespace: ra-completion
  name: ra-completion
type: Opaque
stringData:
  RAUSER: <RetroAchievement.org username>
  RAKEY: <RetroAchievement.org apikey>
  TWITTCK: <Twitter consumer_key>
  TWITTST: <Twitter consumer_secret>
  TWITTAT: <Twitter access_token>
  TWITTTS: <Twitter access_token_secret>
