apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ra-completion-code-perl
spec:
  storageClassName: csi-cinder-classic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
