apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ra-completion-sqlite-db
spec:
  storageClassName: cinder-classic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
